- final/US/CA/KLAX.txt
- final/US/CA/KLAX_readme.md
```
Changes to be committed:
modified:   final/US/CA/KLAX.txt
modified:   final/US/CA/KLAX_readme.md
```
Changelog
> 1.2 - 7/31/2020 - Added KHHR support for increased GA traffic.
> On branch klax

- final/EU/ES/LEMD.txt
Hi,
I have recently modified the LEMD automatically generated file and added runway configurations, entry points, airlines, etc. There is still some work to do, (mainly SIDs, transitions or even _more airlines_), but it is currently playable and I wanted to contribute it.
-Beren
> Added LEMD (Madrid) airport, and thus created EU/ES folder

- README.md
1. Added a request for gameplay and development guides as well as testers.
2. Added links to continent and country/state codes as well as the option for 1 level lower
3. Clarified that airports must end with .txt
> iss13 readme better welcome and naming guidelines

- final/US/CA/KLAX.txt
- final/US/CA/KLAX_readme.md
Finally got the changes I wanted implemented to my KLAX!
Updates:
- Aircraft types and airlines updated.
- Entry points changed to make the game more playable.
- Replaced the old "SIDS" with 15 accurate SIDS! 5 for KLAX, 6 for KLGB, and 4 for KBUR.
Still got a few more things that it needs but I'm so happy to finally get SoCal to a place I am happy with! Its been a mighty project getting this thing done!
> KLAX Version 1.3

- final/EU/NL/EHAM.txt
- final/EU/NL/EHAM_readme.md
> EHAM Update v0.4

- .gitignore
- final/AS/JPN/RJTT.txt
- final/AS/JPN/RJTT_readme.md
- final/AS/JPN/RJTT_readme_JA.md
- final/AS/JPN/source/RJTT.txt
- tools/README.md
- tools/deploy.py
- tools/expand.py
- tools/renumber.py
- Fixed bug where `JCG` would not spawn at `RJTT`.
- Converted source file to new source format
> RJTT ACA 2.2.2

- tools/expand.py
- Add check for self-referencing `[approach]` and throw exception
...because I managed to do this myself. 😓
> Very small update to tools

- final/EU/FIN/EFOU.txt
- final/EU/FIN/EFOU_readme.md
Heres oulu airport in northern finland
> efou airport

- final/AS/HKG/VHHH_mobile_readme.md
Typo Correction, and Correction of Markdown Format
> v1.4.2 README update (VHHH_TMA_Mobile)

- final/AS/CHN/ZY/ZYTL.txt
- final/AS/CHN/ZY/ZYTL_Readme.md
1. Add extra airlines as real world.     
2. Add fixes in ZYTL TMA as charts.
> update ZYTL 1.2 - 4/10/2021

- final/AS/CHN/ZY/ZYTL.txt
- final/AS/CHN/ZY/ZYTL_Readme.md
1. Add controller frequency.(latest version Endless ATC inneed)
2. Modify the final of rwy 28.
3. Modify airspace altitude.
4. Modify initial altitude.
Co-Authored-By: savoki0216 <38267798+savoki0216@users.noreply.github.com>
> ZYTL Update v1.3

- final/NA/USA/PA/KRVL.txt
> KRVL - Mifflin County Airport

- final/AS/SIN/WSSS.txt
> KJ glidepath is out of airspace at WSSS

- final/AS/AFG/OAKB.txt
...and some minor fixes.
Tested on Android.
> Kabul: add terrain and approach paths

- final/EU/BIKF/BIKF.txt
Add airlines, change airline rates, change elevation to match real life, change transition alt to match charts
> BIKF adjustments

- final/NA/POTOMAC/Potomac.txt
Changed IAD to Potomac and changed CSS Callsign
> Potomac Edit

- README.md
Mostly just testing the PR webhook
> Add Discord credit

- final/NA/KEWR2/KEWR2.txt
Added in my version of KEWR with additional airports and configs, as mentioned in #197
> My take on KEWR

- final/EU/EHAA/EHAA.txt
> EHAA bug fixes; closes #204

- final/NA/KBDL/KBDL.txt
- final/NA/KBDL/KBDL_readme.md
Implements a combined Y90 TRACON airspace configuration with KBDL, KBAF, KCEF, KORH and KHFD
> Add KBDL and Y90 (Yankee Approach)

- final/NA/KBTV/KBTV.txt
- final/NA/KBTV/KBTV_readme.md
I think this is good to go, but I'll take feedback.  Not sure if I should try to implement KFSO as well, but I don't think it gets much traffic and it wouldn't really add anything to the current implementation.
> Add WIP BTV APCH

- final/NA/KBDL/KBDL.txt
- final/NA/KBDL/KBDL_readme.md
- final/NA/KBTV/KBTV.txt
- final/NA/KBTV/KBTV_readme.md
Tweaks to KBDL and KBTV to make them more accurate and take advantage of the new changes in V5.0
> Update KBTV and KBDL

- final/NA/KBHM/KBHM.txt
The KBHM sector, including BHM, TCL, GAD, EKY, PLR.
> Initial release of KBHM

- final/AS/RPLL/RPLL.txt
> Updated RPLL

- final/EU/LEBB/LEBB_v0.1.txt
Descent altitudes corrected to make aircraft sequencing more realistic
> iss#255/LEBB_descent_altitudes - closes iss#255

- final/AS/WSSS/WSSS.txt
- final/AS/WSSS/WSSS_readme.md
Initial release of Singapore TMA (version 2.0)
Refer to WSSS_readme.md for more information!
> 282/WSSS - closes 282

- final/EU/London Control/EGTT-N.txt
Added EGNS (Isle of man), Updated the boundary, Added holds for liverpool.
> Update to EGTT-N

- final/EU/EGPH/EGPH.txt
- final/EU/EGPH/EGPH_readme.txt
> Completion of EGPH

- example.txt
New features for Endless ATC v5.6: https://store.steampowered.com/news/app/666610/view/4204754268635768892
> Update example.txt to v5.6
